name: Recovery Building

on: [push]
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkout
         uses: actions/checkout@master

       - name: Reclaiming disk space on / by disabling swap partition
         run: |
               sudo swapoff -av
               sudo rm -f /swapfile;

       - name: Reclaiming disk space on / by removing .NET framework
         run: |
               sudo rm -rf /usr/share/dotnet

       - name: Creating secondary disk folder on /dev/disk/azure/resource-part1 (SSD)
         run: |
              sudo mkdir -p /extended_data
              sudo chown -R runner:docker /extended_data

       - name: On SSD - Creating symlink on /dev/disk/azure/root-part1 pointing to /dev/disk/azure/resource-part1
         run: |
               sudo ln -s /extended_data /mnt/secondary_disk
               sudo ln -s /mnt/secondary_disk $GITHUB_WORKSPACE/

       - name: Creating cache folder on /dev/disk/azure/resource-part1 (SSD)
         run: |
               sudo mkdir -p /mnt/cache
               sudo chown -R runner:docker /mnt/cache

       - name: Creating symlink in $HOME/cache pointing to cache on /dev/disk/azure/resource-part1
         run: |
               ln -s /mnt/cache $HOME/

       - name: Save more space
         run: |
              sudo rm -rf "/usr/local/share/boost"
              sudo rm -rf "$AGENT_TOOLSDIRECTORY"
              sudo swapoff -av
              sudo rm -rf /mnt/swapfile
              sudo apt-get remove -y '^ghc-8.*' '^dotnet-.*' '^llvm-.*' 'php.*' azure-cli google-cloud-sdk '^google-.*' hhvm google-chrome-stable firefox '^firefox-.*' powershell mono-devel '^account-plugin-.*' account-plugin-facebook account-plugin-flickr account-plugin-jabber account-plugin-salut account-plugin-twitter account-plugin-windows-live account-plugin-yahoo aisleriot brltty duplicity empathy empathy-common example-content gnome-accessibility-themes gnome-contacts gnome-mahjongg gnome-mines gnome-orca gnome-screensaver gnome-sudoku gnome-video-effects gnomine landscape-common libreoffice-avmedia-backend-gstreamer libreoffice-base-core libreoffice-calc libreoffice-common libreoffice-core libreoffice-draw libreoffice-gnome libreoffice-gtk libreoffice-impress libreoffice-math libreoffice-ogltrans libreoffice-pdfimport libreoffice-style-galaxy libreoffice-style-human libreoffice-writer libsane libsane-common mcp-account-manager-uoa python3-uno rhythmbox rhythmbox-plugins rhythmbox-plugin-zeitgeist sane-utils shotwell shotwell-common telepathy-gabble telepathy-haze telepathy-idle telepathy-indicator telepathy-logger telepathy-mission-control-5 telepathy-salut totem totem-common totem-plugins printer-driver-brlaser printer-driver-foo2zjs printer-driver-foo2zjs-common printer-driver-m2300w printer-driver-ptouch printer-driver-splix

       - name: Initializing telegram bot
         run: |
              sed -i "s/enzomacaco/$TOKEN/" config.sh
              sed -i "s/enso/$CHATS/" config.sh
              chmod +x -R *.sh
              mkdir -p ~/tmp/; mv config.sh ~/tmp/; mv telegram ~/tmp/
              
       - name: Execute Shell Script
         env:
              RECOVERY: TWRP
              VERSION: 10.0
              DEVICE: f41

         run: |
               cd $RECOVERY/$VERSION/$DEVICE
               chmod +x *.sh
               ./auto.sh
