name: Recovery Building

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
       - uses: actions/checkout@master

       - uses: rokibhasansagar/slimhub_actions@main

       - name: Reclaiming disk space on / by disabling swap partition
         run: |
               sudo swapoff -av
               sudo rm -f /swapfile

       - name: Reclaiming disk space on / by removing .NET framework
         run: |
               sudo rm -rf /usr/share/dotnet

       - name: Save more space
         run: |
              sudo rm -rf "/usr/local/share/boost"
              sudo rm -rf "$AGENT_TOOLSDIRECTORY"
              sudo dd if=/dev/zero of=swap bs=4k count=1048576
              sudo mkswap swap
              sudo swapon swap

       - name: Initializing telegram bot
         env:
              TOKEN: ${{ secrets.TOKEN }}
              CHATS: ${{ secrets.CHATS }}

         run: |
              sed -i "s/enzomacaco/$TOKEN/" config.sh
              sed -i "s/enso/$CHATS/" config.sh
              chmod +x -R *.sh
              mkdir -p ~/tmp/; mv config.sh ~/tmp/; mv telegram ~/tmp/

       - name: Execute Shell Script
         env:
              RECOVERY: TWRP
              VERSION: "10.0"
              DEVICE: m11q

         run: |
               cd $RECOVERY/$VERSION/$DEVICE
               chmod +x *.sh
               ./auto.sh
         
       - name: Release Builds
         uses: "marvinpinto/action-automatic-releases@latest"
         with:
          repo_token: "${{ secrets.GHT }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Recovery Files"
          files: |
            $RECOVERY/out/target/product/$DEVICE/*.zip
            $RECOVERY/out/target/product/$DEVICE/*.zip
