name: Recovery Building

on: [push]
  
jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
       - name: Checkout
         uses: actions/checkout@master

       - name: Reclaiming disk space on / by disabling swap partition
         run: |
               sudo swapoff -av
               sudo rm -f /swapfile;

       - name: Reclaiming disk space on / by removing .NET framework
         run: |
               sudo rm -rf /usr/share/dotnet

       - name: Save more space
         run: |
              sudo rm -rf "/usr/local/share/boost"
              sudo rm -rf "$AGENT_TOOLSDIRECTORY"
              sudo swapoff -av
              sudo rm -rf /mnt/swapfile
              sudo apt-get remove -y '^ghc-8.*' '^dotnet-.*' '^llvm-.*' 'php.*' azure-cli google-cloud-sdk '^google-.*' hhvm google-chrome-stable firefox '^firefox-.*' powershell mono-devel '^account-plugin-.*' account-plugin-facebook account-plugin-flickr account-plugin-twitter account-plugin-windows-live aisleriot brltty duplicity empathy empathy-common example-content gnome-accessibility-themes gnome-contacts gnome-mahjongg gnome-mines gnome-orca gnome-screensaver gnome-sudoku gnome-video-effects gnomine landscape-common libreoffice-avmedia-backend-gstreamer libreoffice-base-core libreoffice-calc libreoffice-common libreoffice-core libreoffice-draw libreoffice-gnome libreoffice-gtk libreoffice-impress libreoffice-math libreoffice-ogltrans libreoffice-pdfimport libreoffice-style-galaxy libreoffice-style-human libreoffice-writer libsane libsane-common python3-uno rhythmbox rhythmbox-plugins rhythmbox-plugin-zeitgeist sane-utils shotwell shotwell-common telepathy-gabble telepathy-haze telepathy-idle telepathy-indicator telepathy-logger telepathy-mission-control-5 telepathy-salut totem totem-common totem-plugins printer-driver-brlaser printer-driver-foo2zjs printer-driver-foo2zjs-common printer-driver-m2300w printer-driver-ptouch printer-driver-splix
              # Bonus
              sudo dd if=/dev/zero of=swap bs=4k count=1048576
              sudo mkswap swap
              sudo swapon swap

       - name: Initializing telegram bot
         env:
              TOKEN: ${{ secrets.TOKEN }}
              CHATS: ${{ secrets.CHATS }}

         run: |
              sed -i "s/enzomacaco/$TOKEN/" config.sh
              sed -i "s/enso/$CHATS/" config.sh
              chmod +x -R *.sh
              mkdir -p ~/tmp/; mv config.sh ~/tmp/; mv telegram ~/tmp/
              
       - name: Execute Shell Script
         env:
              RECOVERY: OFR
              VERSION: "9.0"
              DEVICE: a20

         run: |
               cd $RECOVERY/$VERSION/$DEVICE
               chmod +x *.sh
               ./auto.sh
